#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	state=`pgrep -f "/usr/speedtest-go/speedtest"`
	if [ ! -z "$state" ]; then
		restart
	else
		/usr/speedtest-go/speedtest &
	fi
	echo "speedtest is starting now ..."
}

stop() {
	kill -9 `pgrep -f "/usr/speedtest-go/speedtest"` 2>/dev/null
	echo "speedtest exit ..."
}

restart(){
	stop
	sleep 1
	start
	echo "restarted."
}